### ISSUE TITLE
[Setting] 프로젝트 초기세팅

### ISSUE THREAD

**Issue by Heyjooo** [GO-SOPT-SOLSOL/SOLSOL-iOS#1]
## 🛠 Issue
issue, pull_request template 생성
storyboard 제거
라이브러리 설치
폴더구조 생성
SceneDelegate 수정
DesignSystem 설정

## 📝 To-do
- [x] issue, pull_request template 생성
- [x] storyboard 제거
- [x] 라이브러리 설치(SnapKit, Then, Alamofire)
- [x] 폴더구조 생성
- [x] SceneDelegate 수정
- [x] DesignSystem 설정 (font, color, assets)
