### ISSUE TITLE
[Feat] transfer section 제외 모든 section 구현

### ISSUE THREAD

**Issue by Heyjooo** [GO-SOPT-SOLSOL/SOLSOL-iOS#16]
## 🛠 Issue

- section shinhanPlus, category, footerButton 구현
- SOL button 컴포넌트 사용

## 📝 To-do

- [ ] section shinhanPlus 구현
- [ ] section category 구현
- [ ] section footerButton 구현
- [ ] SOL 버튼 컴포넌트 사용
