### ISSUE TITLE
[Feat] HomeViewController 전체적인 구조 구현

### ISSUE THREAD

**Issue by Heyjooo** [GO-SOPT-SOLSOL/SOLSOL-iOS#3]
## 🛠 Issue

- TableView로 전체적인 구조 잡기
- section 나누기
- section 0,1,4 구현
- section 2,3,5,6 전체적인 구조 잡기

## 📝 To-do

- [x] TableView로 전체적인 구조 잡기
- [x] section 0~6로 나누기
- [x] section 0,1 구현
- [x] section 2,3 전체적인 구조 잡기
- [x] section 4 구현
- [x] secion 5,6 전체적인 구조 잡기
