### ISSUE TITLE
[Feat] tableView background 클릭 시 키보드 내리기, segmentControl에 View 넣기

### ISSUE THREAD

**Issue by sjk4618** [GO-SOPT-SOLSOL/SOLSOL-iOS#33]
## 🛠 Issue

- tableView background 클릭 시 키보드 내리기
- SegmentControl 클릭 시 키보드 내리기
- segmentControl에 tableView 와 view 넣기

## 📝 To-do

- [x] tableView background 클릭 시 키보드 내리기
- [x] SegmentControl 클릭 시 키보드 내리기
- [ ]  segmentControl에 tableView 와 view 넣기
