### ISSUE TITLE
[Feat] 서버통신 🚨

### ISSUE THREAD

**Issue by Heyjooo** [GO-SOPT-SOLSOL/SOLSOL-iOS#38]
## 🛠 Issue

- TableView Advertisement section Cell에 서버통신 data 뿌리기
- TableView 안의 CollectionView Cell에 서버통신 data 뿌리기
- TableView 안의 CollectionView의 CollectionView Cell에 서버통신 data 뿌리기

## 📝 To-do

- [x] TableView Advertisement section Cell에 서버통신 data 뿌리기
- [x] TableView 안의 CollectionView Cell에 서버통신 data 뿌리기
- [x] TableView 안의 CollectionView의 CollectionView Cell에 서버통신 data 뿌리기
